book = {
    1: """Située au nord de la région de Liyue, la forêt de pierre de Jueyun est couverte par la brume. Les légendes regorgent parmi les herboristes locaux, qui content maintes histoires d’Adeptes et d’esprits malins.
L’on raconte par exemple l’histoire de ce marchand d’herbes médicinales nommé Qiangu, venu inspecter la distribution des herbes au Karst Jueyun. À sa, grande ignorance, des brigands le suivirent à travers la montagne, puis, la nuit venue, l’assommèrent et le dépouillèrent, le laissant ligoté dans la vallée.
Reprenant conscience au milieu de la nuit, le marchand tenta de venir à bout de ses liens, appelant à l’aide. Mais aucune réponse ne vint des montagnes, si ce n’est l’écho de ses appels dérangeant une nuée d’oiseaux au loin.
Alors qu’il s’apprêtait à céder au désespoir, une voix ancienne se fit entendre à travers le bruit du vent et le hululements des chouettes.
« Lève-toi !
– Je ne peux pas ! », sanglota-t-il, effrayant au passage un renard qui venait à passer par là. Mais alors qu’il se débattait à nouveau, il réalisa que ses liens étaient soudain beaucoup plus lâches.
Se relevant, il n’eut pas le temps d’ouvrir la bouche pour exprimer sa reconnaissance.
« Grimpe la montagne. »
Qiangu s’enfonça dans les chemins sinueux, et atteint le sommet de la montagne ; à l’est le soleil pointait. Observant les alentours, il aperçut alors un vieux pin sec et flétri poussant au rebord du précipice. À ses branches étaient suspendus les bandits ligotés, leur balancement faisant gémir les branches les supportant.
Sur un rocher de forme étrange peu loin était assis un vieil homme, à la barbe et aux cheveux blancs comme la neige. À la vue de l’expression affolée de Qiangu, le vieillard se mis à rire à gorge déployée, et lui remit toutes ses possessions.
Interrogé par Qiangu, l’homme répondit qu’il était natif de la montagne : sa maison était là où le portait ses pas et il dormait où il s’allongeait. Le marchand se fondit en remerciements, cherchant à exprimer sa gratitude par tous les moyens ; mais le vieil homme refusa toute récompense, n’acceptant qu’une pièce d’un mora, à utiliser pour pouvoir participer au mariage futur de la fille du marchand.
Suite à cet incident, et peut-être à cause de lui, les affaires se mirent à fleurir pour Qiangu, et sa réputation de marchand grandit dans les environs du port de Liyue. Certains racontent qu’une fois sa fortune établie, Qiangu revint à l’endroit de son étrange rencontre, mais ne trouva rien d’autre que quelques tentes et bouteilles abandonnées. D’autres prétendent avoir aperçu le vieillard aux Bancs de Yaoguang, déguisé en mineur, se déplaçant entre les précipices comme porté par les vents ; d’autres encore qu’il s’agit d’un pêcheur venant en aide à ceux tombés en mer. Nombreuses sont les histoires circulant sur son compte ; mais le nom du vieillard reste inconnu de tous.
Hélas, Qiangu est aujourd’hui rejoint par les années, et sa fille chérie demeure célibataire. Qui sait ? Peut-être un jour se mariera-t-elle, et verra-t-on assister à la cérémonie le vieillard de la montagne ; mais avec le temps qui passe, les chances que cela arrive s’amenuisent de jour en jour.""",

    2: """La région connue sous le nom de « Plaines Guili » était autrefois recouverte de lys vernis. Mais, cernés par les troubles de toute part, ses anciens habitants n’eurent d’autre choix que de fuir, et, conséquence de la prospérité du Port de Liyue, d’autres prirent leur place avec le temps. Mais nombre d’histoires de chevalerie continuent d’y circuler encore aujourd’hui.

Les marchands itinérants et les porteurs racontent ainsi l’histoire de cette mystérieuse silhouette qui apparaissait autrefois au plus profond de la nuit dans les plaines. Ils racontent qu’il s’agissait d’une femme vêtue d’une longue robe indigo, avançant le long de la rivière Bishui, le visage baigné par la clarté argentée de la lune, tandis que la nuit emportait ses mots jusqu’aux cieux et aux étoiles qui jamais ne dorment.

D’après certains clients de l’Auberge Wangshu, seuls ceux qui se perdaient au milieu des lucioles les nuits d’été avaient une chance de l’apercevoir, et seuls ceux capables de distinguer la fragrance du lys verni au milieu des lucioles et des Fées dansantes pouvaient trouver sa trace. D’aucuns supposent qu’il s’agissait là de quelque bête mystique ancienne, ou de quelque servante d’un dieu oublié depuis longtemps portant le deuil de son maître la nuit venue. Il en est même qui pensent que la femme était un chevalier errant, qui, comme nombre de chevaliers errants, abandonna la civilisation et cacha son vrai nom.

Nul ne sait où commence son histoire, mais elle trouve sa fin dans le récit d’un chasseur. Or, contrairement aux histoires racontée par les marchands itinérants, le chasseur fit la rencontre de la femme alors qu’elle se battait à l’épée contre plusieurs ombres menaçantes sous la clarté impitoyable de la lune. Après sa danse élégante et mortelle, elle disparut, ne laissant derrière elle que poussière et sang. Le jour suivant, des citoyens découvrirent les corps de soldats Millelithes et de géomètres le long de la rivière. Le Bureau des Affaires Civiles, suite à cet événement, entreprit à plusieurs reprises des recherches. Mais nul ne revit plus jamais la silhouette de la femme.

Peut-être que la danse mortelle était le fruit de quelque vendetta, ou peut-être que la femme était un genre de brigand. Ou peut-être encore, ceci ne requiert ni raison ni excuse. Si les héros sont des héros, c’est qu’ils utilisent leurs épées pour des raisons dépassant souvent l’entendement.

Mais à mesure que les lumières de Liyue recouvraient les villages désertés, cette légende finit à son tour par disparaître. On raconte cependant que les rives le long desquelles marchait autrefois la femme continuent de nos jours à foisonner de lys vernis."""
}