from commands.help import Help
from commands.idtotime import IdToTime
from commands.magie import Magie
from commands.serverstat import ServerStat
from commands.showartifacts import ShowArtifacts
from commands.showcollection import ShowCollection
from commands.showquestbooks import ShowQuestBooks
from commands.getid import GetId
from commands.vote import Vote
from commands.sendlink import SendLink
